services:
  chat-app-postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - my-postgres_data:/var/lib/postgresql/data

volumes:
  my-postgres_data:
    driver: local
